server:
  port: 8085

spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
  #注册到zookeeper地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
