server:
  port: 80

spring:
  application:
    name: cloud-consulconsumer-order
  cloud:
  #注册到zookeeper地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
